#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: HZN-WEB | status | Print service being checked
  debug:
    msg: "Running service check for HZN-WEB"
  run_once: true

- name: HZN-WEB | status | Check system service running
  command: systemctl status apache2
  ignore_errors: yes
  changed_when: false
  register: systemctl_apache_status_result

- name: HZN-WEB | status | Report status of apache2
  fail:
    msg: |
      apache2 is not running
      systemctl status apache2 output:
      {{ systemctl_apache_status_result.stdout }}
      {{ systemctl_apache_status_result.stderr }}
  when: systemctl_apache_status_result | failed

- name: HZN-WEB | status | (Debian) Check status of horizon vhost
  become: yes
  shell: . /etc/apache2/envvars && /usr/sbin/apache2 -S | grep 'horizon.conf'
  ignore_errors: yes
  register: sbin_apache2_status_result
  when: ansible_os_family == 'Debian'

- name: HZN-WEB | status | (Debian) Report status of horizon vhost
  fail:
    msg: |
      horizon vhost is not enabled
  when:
    ansible_os_family == 'Debian' and
    sbin_apache2_status_result.stdout == ""

- name: HZN-WEB | status | (Suse) Check status of horizon vhost
  become: yes
  shell: /usr/sbin/apachectl -S 2>/dev/null | grep 'horizon.conf'
  ignore_errors: yes
  register: sbin_apachectl_status_result
  when: ansible_os_family == 'Suse'

- name: HZN-WEB | status | (Suse) Report status of horizon vhost
  fail:
    msg: |
      horizon vhost is not enabled
  when:
    ansible_os_family == 'Suse' and
    sbin_apachectl_status_result.stdout == ""
